# Generated by Django 2.1 on 2018-09-02 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webClass', '0002_projects_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='description',
            new_name='desc',
        ),
    ]
